config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                      root GET    /                                                                                        pages#home
#                   contact GET    /contact(.:format)                                                                       pages#contact
#               sponsorship GET    /sponsorship(.:format)                                                                   pages#sponsorship
#                      team GET    /team(.:format)                                                                          pages#team
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :posts, only: %I[index show]
  get :contact, to: 'pages#contact'
  get :sponsorship, to: 'pages#sponsorship'
  get :team, to: 'pages#team'

  namespace :ticketing, path: 'billetterie' do
    root to: 'items#index'
    resources :tickets, only: %I[create show]
    get '/:ticket_id/merci', to: 'tickets#thank_you', as: :thank_you
  end

  authenticate :user, ->(u) {u.admin} do
    namespace :admin do
      root to:'posts#new'
      resources :posts, only: %I[new create edit update destroy]
    end
  end
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,184,169,0.2) 0%, rgba(0,79,73,0.1) 50%), url(<%= asset_path 'banner-owl.png' %>);">
  <div class="banner-content">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h1 class="text-center">
              LE PARC SAUVAGE
            </h1>
            <%= render "shared/features" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_features.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-md-6">
      <div class="feature-card text-center">
        <a href="/#ferme">
          <div class="feature-card-img d-flex align-items-center justify-content-center">
            <%= image_tag "rabbit.png" %>
            <!-- <img src="https://png.icons8.com/cotton/100/000000/certificate.png"> -->
          </div>
        </a>
        <div class="feature-card-body">
          <div class="feature-card-body-title">
            <h3>Mini-ferme pédagogique</h3>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="feature-card text-center">
        <a href="/#fauconnerie">
          <div class="feature-card-img d-flex align-items-center justify-content-center">
            <%= image_tag "eagle.png" %>
            <!-- <img src="https://png.icons8.com/cotton/100/000000/create-new.png"> -->
          </div>
        </a>
        <div class="feature-card-body">
          <div class="feature-card-body-title">
            <h3>Fauconnerie</h3>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="feature-card text-center">
        <a href="/#vision">
          <div class="feature-card-img d-flex align-items-center justify-content-center">
            <%= image_tag "goat.png" %>
            <!-- <img src="https://png.icons8.com/cotton/100/000000/clouds.png"> -->
          </div>
        </a>
        <div class="feature-card-body">
          <div class="feature-card-body-title">
            <h3>Parc de vision</h3>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="feature-card text-center">
        <a href="/#sauvegarde">
          <div class="feature-card-img d-flex align-items-center justify-content-center">
            <%= image_tag "owl2.png" %>
            <!-- <img src="https://png.icons8.com/cotton/100/000000/clouds.png"> -->
          </div>
        </a>
        <div class="feature-card-body">
          <div class="feature-card-body-title">
            <h3>Centre de Sauvegarde</h3>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible <%= current_page?(root_path) ? 'alert-marged' : '' %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible <%= current_page?(root_path) ? 'alert-marged' : '' %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/circasvolerie/" target="_blank"><i class="fab fa-instagram" ></i></a>
    <a href="https://www.facebook.com/jack.parcsauvage.1?ref=br_rs" target="_blank"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-twitter" target="_blank"></i></a>
  </div>
  <div class="footer-copyright">
    Ce site a été fait avec <i class="fa fa-heart"></i> par Carine Sybille Claire Stéphane & Théophane
  </div>

  <div class="footer-sign-in-out">
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete, class: "footer-sign-in-out", style: 'color:#f5f9fa;' do %>
      <i class="fas fa-sign-out-alt"></i>
      <span> <%= t(".sign_out", default: "Déconnexion") %>
      </span>
    <% end %>
  <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <% end %>

  </div>


</div>

app/views/shared/_home_post.html.erb
<div class="wrapper-feed">
<div class="row">
  <div class="col text-center">
    <h2 class="mb-3">Actualités du parc</h2>
  </div>
</div>
<div class="row row-feed">
  <% Post.all.order(created_at: :desc).last(4).each do |post| %>
  <div class="col">
    <div class="display-feed">
      <%= link_to post_path(post), style: "color:$parc-black !important;" do%>
      <div class="photo-index-new">
        <%= image_tag(url_for(post.photo)) %>
      </div>
      <div  class= "title-feed" ><%= post.title %></div>
      <%= link_to "Lire la suite", post_path(post), class: "button", id:"button-news"%>
      <% end %>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-default navbar-static-top <%= current_page?(root_path) ? "navbar-fixed-top" : "navbar-wagon-white" %>">
  <!-- Logo & Name -->
  <div class="navbar-left">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "owl.png", height: 50 %>
    <% end %>
<!--     <div class="navbar-typo">
     <span>Le Parc Sauvage</span>
    </div> -->
  </div>


 <!-- Right Navigation -->
 <div class="navbar-wagon-right hidden-xs hidden-sm navbar-wagon-link">

  <!-- Links when logged in -->
  <%= link_to "Billetterie", ticketing_root_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "Blog", posts_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "Equipe", team_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "Parrainage", sponsorship_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-wagon-link" %>

  </div>

</div>