config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                      root GET    /                                                                                        pages#home
#                   contact GET    /contact(.:format)                                                                       pages#contact
#               sponsorship GET    /sponsorship(.:format)                                                                   pages#sponsorship
#                      team GET    /team(.:format)                                                                          pages#team
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :posts, only: %I[index show]
  get :contact, to: 'pages#contact'
  get :sponsorship, to: 'pages#sponsorship'
  get :team, to: 'pages#team'

  namespace :ticketing, path: 'billetterie' do
    root to: 'items#index'
    resources :tickets, only: %I[create show]
    get '/:ticket_id/merci', to: 'tickets#thank_you', as: :thank_you
  end

  authenticate :user, ->(u) {u.admin} do
    namespace :admin do
      root to:'posts#new'
      resources :posts, only: %I[new create edit update destroy]
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  content    :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :set_post, only: %I[edit update destroy]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render "posts/new"
    end
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :title, :user_id, :photo)
  end

  def check_admin?
    current_user.admin
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %I[show edit update destroy]

  skip_before_action :authenticate_user!, only: %I[index show]
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render "posts/new"
    end
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :title, :user_id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.input :title, label: "Titre" %>
  <%= f.input :content, as: :text %>
  <%= f.button :submit, value: 'Publier cet article'%>
<% end %>

<%= link_to "Retour à tous les articles", posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="wrap-contact">
    <div class="presentation text-center">
      <div class="row">
        <div class="col">
        <h2>Les actualités du Parc Sauvage</h2>

        <% @posts.each do |post| %>
        <div class="post-card-index">
          <div class="post-title-index">
            <%= post.title %>
          </div>
          <div class="card-inside d-flex">
            <div class="photo-index">
              <%= image_tag(url_for(post.photo))%>
            </div>
            <div class="post-content-index">
              <%= post.content.first(400) %> (...)
              <div class="card-button">
                <%= link_to "Lire la suite", post_path(post), class: "button content-btn" %>
              </div>
            </div>
          </div>
        </div>
        <% end %>

        <% if user_signed_in? and current_user.admin? %>
            <div class="index-link">
              <%= link_to "Ajouter un article", new_admin_post_path, class: "button card-button" %>
            </div>
        <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">

      <div class="post-card-index">
        <div class="post-title-index">
          <div class="post-title-index">
            <%= @post.title %>
          </div>
          <div class="card-inside d-flex">
            <div class="photo-show">
              <%= image_tag(url_for(@post.photo))%>
            </div>
            <div class="post-content-index">
              <%= @post.content %> <br>
            </div>
          </div>

          <% if user_signed_in? and current_user.admin? %>

            <%= link_to "Modifier mon article", edit_admin_post_path(@post), class: "button" %>
            <%= link_to "Supprimer cet article", admin_post_path(@post), method: :delete, data: { confirm: "Confirmer la suppression de cet article ?" }, class: "button" %>

          <% end %>


          <br>
            <%= link_to "Retour à tous les articles", posts_path, class: "button" %>
        </div>
      </div>

    </div>
  </div>
</div>