config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                      root GET    /                                                                                        pages#home
#                   contact GET    /contact(.:format)                                                                       pages#contact
#               sponsorship GET    /sponsorship(.:format)                                                                   pages#sponsorship
#                      team GET    /team(.:format)                                                                          pages#team
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :posts, only: %I[index show]
  get :contact, to: 'pages#contact'
  get :sponsorship, to: 'pages#sponsorship'
  get :team, to: 'pages#team'

  namespace :ticketing, path: 'billetterie' do
    root to: 'items#index'
    resources :tickets, only: %I[create show]
    get '/:ticket_id/merci', to: 'tickets#thank_you', as: :thank_you
  end

  authenticate :user, ->(u) {u.admin} do
    namespace :admin do
      root to:'posts#new'
      resources :posts, only: %I[new create edit update destroy]
    end
  end
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :bigint(8)        not null, primary key
#  i_type      :integer
#  name        :string
#  price_cents :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Item < ApplicationRecord
  has_many :tickets, dependent: :nullify

  monetize :price_cents

  enum i_type: { individual: 0, grouped: 1 }

  def format_price
    Money.new(price_cents, 'EUR').format(symbol_position: :after, display_free: 'gratuit')
  end
end

app/controllers/ticketing/items_controller.rb
module Ticketing
  class ItemsController < ApplicationController
    def index
      @individual_items = Item.individual
      @group_items = Item.grouped
    end
  end
end

app/controllers/ticketing/tickets_controller.rb
module Ticketing
  class TicketsController < ApplicationController
    before_action :set_ticket, only: %I[show]
    def create
      @ticket = Ticket.create(
        stripe_token: ticket_params[:stripeToken],
        code: Devise.friendly_token,
        user: current_user,
        item_id: ticket_params[:item_id],
        from: ticket_params[:from],
        to: ticket_params[:to]
      )
      redirect_to ticketing_thank_you_path(@ticket)
    end

    def thank_you
      @ticket = Ticket.find(params[:ticket_id])
    end

    def show
      respond_to do |format|
        format.pdf { render pdf: "#{current_user.full_name}_#{Date.today.strftime("%d_%m_%Y")}_#{@ticket.item.price_cents}" }
      end
    end

    private

    def ticket_params
      params.permit(:stripeToken, :item_id, :from, :to)
    end

    def set_ticket
      @ticket = Ticket.find(params[:id])
    end
  end
end

app/views/ticketing/items/_stripe_form.html.erb
<form action="<%= ticketing_tickets_path %>" method="POST">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :item_id, item.id %>
  <input type="hidden" name="from" class="stripe-from">
  <input type="hidden" name="to" class="stripe-to">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_632flUKgRrL9NaJO3sPfosY3"
    data-amount="<%= item.price_cents %>"
    data-name="Le Parc Sauvage"
    data-email="leparczoo@gmail.fr"
    data-description="<%= item.name %>"
    data-image="<%= image_path('owl.png') %>"
    data-locale="fr"
    data-currency="eur">
  </script>
</form>

app/views/ticketing/items/index.html.erb
<div class="container">
  <div class="wrap-contact">
    <div class="row">
      <div class="col">
        <h1>Dates de visites</h1>
      </div>
    </div>
      <%= simple_form_for :dates do |f| %>
        <div class="row">
          <div class="col">
            <%= f.input :from, label: 'du', input_html: { class: 'datepicker' } %>
          </div>
          <div class="col">
            <%= f.input :to, label: 'au', input_html: { class: 'datepicker' } %>
          </div>
        </div>
      <% end %>
    <div class="row">
      <div class="col">
        <table class="table table-bordered table-stripped">
          <thead>
            <tr>
              <th scope="col">Tarifs Individuels</th>
              <th>Prix</th>
            </tr>
          </thead>
          <tbody>
            <% @individual_items.each do |item| %>
              <tr class="text-center">
                <td scope="row"><%= item.name %></td>
                <td>
                  <%= item.format_price %>
                  <% unless item.format_price == 'gratuit' %>
                  <%= render 'stripe_form', item: item %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <table class="table table-bordered table-stripped">
          <thead>
            <tr>
              <th scope="col">Tarifs de groupe</th>
              <th>Prix</th>
            </tr>
          </thead>
          <tbody>
            <% @group_items.each do |item| %>
              <tr class="text-center">
                <td scope="row"><%= item.name %></td>
                <td>
                  <p><input type="number" value="1" class="form-control d-inline" style="width: 100px;"> x <%= item.format_price %></p>
                  <%= render 'stripe_form', item: item %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= content_for :after_js do %>
  <%= javascript_pack_tag('datepicker') %>
  <%= stylesheet_pack_tag('datepicker') %>
<% end %>